### ISSUE TITLE
Gifs not loading all of a sudden.

### ISSUE THREAD

**Issue by 3200pro** [XSlemX/sanity-plugin-asset-source-giphy#6]
I've been using this for a few months on multiple sites with no errors/bugs. It's awesome. Well done:)

I loaded it up on a client site this evening and it's stuck on the loader with the transparent white background. The Gifs don't load and escaping out is the only solution. I've got the API Key loaded up and autoPlay on false. Any suggestions?

**Comment by XSlemX** [comment]
😅 Sorry for the late reply. New version for the upcoming v3 studio is due today. I will try to fix for < 3.

**Comment by XSlemX** [comment]
At second thought, this is so old that I don't want to bother you for details. Hopefully you figured it out.

**Comment by 3200pro** [comment]
Let me know when you get V3 ready and I'll give it a go. Thanks for the response:)

**Comment by XSlemX** [comment]
Out now: https://www.npmjs.com/package/sanity-plugin-asset-source-giphy @3200pro
